config/urls.py
from django.contrib import admin

# from django.urls import path
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

# 개발 환경에서 "[BASE_URL]/uploads" 경로를 찾아... "/media"랑은 무슨 관련이 있징?.?
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

# rooms.views 대신에 rooms_views 를 통해 rooms application을 자동으로 찾아가는건가??
# FBV를 통해 이동
# urlpatterns = [path("", room_views.all_rooms, name="home")]
# CBV를 통해 이동
urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    # path("<int:potato", views.room_detail, name="detail"),
    # front 페이지에서 사용자에게 입력받는 값을 views.py에 전달.
    path("<int:pk>", views.RoomDetail.as_view(), name="detail"),
    path("search/", views.SearchView.as_view(), name="search"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login", views.LoginView.as_view(), name="login"),
    path("logout", views.log_out, name="logout"),
    path("signup", views.SignUpView.as_view(), name="signup")
]

templates/partials/footer.html
<footer>
    &copy; footer - Nbnb
</footer> 

templates/partials/header.html
<header>
    <a href="{% url "core:home" %}">Nbnb</a>
    <ul>
        <li><a href="#">header - Login</a></li>
    </ul>
    <form method="get" action="{% url "rooms:search" %}">
        <input value="Seoul" name="city" placeholder="Search by City" />
    </form>
</header>

templates/partials/nav.html
<a href="{% url "core:home" %}">Nbnb</a>
<ul>

    {% if user.is_authenticated %}
        <li><a href="{% url "users:logout" %}">Log out</a></li>
    {% else %}
        <li><a href="{% url "users:login" %}">Log in</a></li>
        <li><a href="{% url "users:signup" %}">Sign up</a></li>
    {% endif %}

</ul>